apiVersion: v1
kind: Pod
metadata:
  name: cg
  namespace: app
spec:
  containers:
    - name: cg-test-keyless-sign
      image: ghcr.io/anshumaan-10/image-attestation-cosign@<IMAGE_DIGEST>
      resources: {}
