apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-keyless
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: check-image-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - image: "ghcr.io/anshumaan-10/*"
        verifyDigest: true
        attestors:
          - entries:
              - keyless:
                  subject: "https://github.com/anshumaan-10/image-attestation-cosign/.github/workflows/custom-sign.yml@refs/heads/main"
                  issuer: "https://token.actions.githubusercontent.com"
                  rekor:
                    url: "https://rekor.sigstore.dev"
