name: Publish and Sign Container Image

on:
  schedule:
    - cron: '32 11 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.2.0

    - name: Check install!
      run: cosign version

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into ghcr.io
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      id: push-step
      uses: docker/build-push-action@master
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Sign the images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.push-step.outputs.digest }}
        TAGS: ghcr.io/${{ github.repository }}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes "${TAGS}@${DIGEST}"

    - name: (optional) Verify the images
      run: |
        cosign verify ghcr.io/${{ github.repository }}:latest \
           --certificate-identity https://github.com/${{ github.repository }}@refs/heads/main \
           --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq

    - name: Create k3s cluster
      uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'latest'
          
    - name: Install Kyverno chart
      run: |
        helm repo add kyverno https://kyverno.github.io/kyverno/
        helm repo update
        helm install --atomic kyverno kyverno/kyverno -n kyverno --create-namespace
        sleep 10

    - name: Apply image attestation policy
      run: |
        kubectl apply -f ./k3s/policy-check-image-keyless.yaml

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy pod to k3s
      if: always()
      run: |
        ls -larth ./k3s
        kubectl create ns app
        kubectl apply -f ./k3s/pod.yml
        sleep 20
        #kubectl -n app wait --for=condition=Ready pod/cg --timeout=120s
        kubectl get pods -n app
