name: Publish and Sign Container Image

on:
  schedule:
    - cron: '32 11 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install cosign
      uses: sigstore/cosign-installer@v3.2.0

    - name: Verify Cosign installation
      run: cosign version

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      id: push-step
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Sign the image
      env:
        DIGEST: ${{ steps.push-step.outputs.digest }}
        TAGS: ghcr.io/${{ github.repository }}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes "${TAGS}@${DIGEST}"

    - name: Verify the image
      env:
        TAGS: ghcr.io/${{ github.repository }}:latest
      run: |
        cosign verify "${TAGS}" \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/cosign.yml@refs/heads/main" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com"

  deploy-to-k3s:
    needs: build-and-sign
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create k3s cluster
      uses: debianmaster/actions-k3s@master
      with:
        version: 'latest'
      
    - name: Install Kyverno with Helm
      run: |
        helm repo add kyverno https://kyverno.github.io/kyverno/
        helm repo update
        helm install kyverno kyverno/kyverno -n kyverno --create-namespace
        sleep 10

    - name: Apply Kyverno image attestation policy
      run: |
        kubectl apply -f ./k3s/policy-check-image-keyless.yaml

    - name: Deploy pod to k3s
      run: |
        kubectl create ns app
        kubectl apply -f ./k3s/pod.yml
        sleep 20
        kubectl get pods -n app
