name: Publish and Sign Container Image

on:
  schedule:
    - cron: '32 11 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.2.0

      - name: Check install!
        run: cosign version

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: push-step
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Decode cosign private key
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | base64 -d > cosign.key

      - name: Sign the images with Custom Key
        env:
          DIGEST: ${{ steps.push-step.outputs.digest }}
          TAGS: ghcr.io/${{ github.repository }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "Signing the image with custom key..."
          cosign sign --key cosign.key "${TAGS}@${DIGEST}"

      - name: (optional) Verify the images
        run: |
          cosign verify --key cosign.pub ghcr.io/${{ github.repository }}:latest | jq

      - name: Create k3s cluster
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Install Kyverno chart
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo update
          helm install --atomic kyverno kyverno/kyverno -n kyverno --create-namespace
          sleep 10

      - name: Apply image attestation policy
        run: |
          kubectl apply -f ./k3s/policy-check-image-keyless.yaml

      - name: Deploy pod to k3s
        if: always()
        run: |
          kubectl create ns app
          kubectl apply -f ./k3s/pod.yml
          sleep 20
          kubectl get pods -n app

      - name: (optional) Install Kyverno CLI
        if: always()
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.9.5'

      - name: (optional) Dry run policy using Kyverno CLI
        if: always()
        run: |
          kyverno version
          kubectl get clusterpolicies -o yaml | kyverno apply - --resource ./k3s/pod.yml
